### ISSUE TITLE
Swap TFN AR M249s to MG4s

### ISSUE THREAD

**Issue by baegel49** [CntoDev/compositions#182]
Cons (old)
- Potential for sound bugs (resolved with update, MG4 now uses vanilla sounds)

Pros
- TFN is more distinct
- More variety
- @Seb105 can't tell me we don't use BW mod just because he doesn't attend my German army missions
- In line with TFN using Flecktarn, HK416s, and MG5s

**Comment by freghar** [comment]
Pardon the stupid question, but how does MG4 compare to M249 in terms of
* weapon weight
* ammo weight (do we need to shuffle new boxes around?)
* caliber/damage
* difference compared to MMG .. ?

Thanks!

(Just trying to see what would change, can't start Arma right now.)

**Comment by baegel49** [comment]
I can't open up Arma either right now but you'll find the answer to those questions in the editor. 

The gist of it is that it is more or less the same, I believe MG4 bags weigh a bit less but they're the same caliber, which means they have 5.56 caliber compared to MMGs 7.62

**Comment by LongbeardNor** [comment]
MG4 Weapon stats:
ROF: 890 rpm
Accuracy: 0.93
Weight: 8.12 kg
Ammostat:
Type: 5.56x45 200 rnd Belt
Bullet mass 4.0g
Weight: 1.81 kg

M249 Weapon stats:
ROF: 800 rpm
Accuracy: 1.01-1.11 depending on modell
Weight: 5.97kg- 7.35kg depending on modell
Ammostat: This is the stat for 200 rnd M249 Softpack 
Type: 5.56x45 200 rounds 
Bullet mass 4.0g 
Weight: 2.08 kg

**Comment by baegel49** [comment]
Thanks longbeard! @freghar as you can see, its very similar.

Hopefully this alleviates any concerns you had :)

**Comment by JamesTheClarke** [comment]
To-do checklist for relevant commit

- [ ] replace primary weapon AR from M249s to MG4s
- [ ] replace AAR ammo backpack content to fit new requirement
- [ ] replace AR ammo in Fireteam Resupply Box
- [ ] replace AR ammo in Platoon Resupply Crate

**Comment by freghar** [comment]
When replacing boxes, watch out for weight differences, the MG4 200rnd ones aren't exactly double the RHS 100rnd.
```
BWA3_200Rnd_556x45:
- mass: 40
- initSpeed: 920
- ammo: BWA3_B_556x45_Ball
  - typicalSpeed: 920
  - airFriction: -0.00130094
  - caliber: 0.869565
  - hit: 9

rhsusf_100Rnd_556x45_soft_pouch:
- mass: 26.9
- initSpeed: 960
- ammo: rhs_ammo_556x45_M855A1_Ball
  - typicalSpeed: 960
  - airFriction: -0.000772
  - caliber: 0.65
  - hit: 9
```
