### ISSUE TITLE
Use stronger 5.56mm bullets for US/TFN

### ISSUE THREAD

**Issue by freghar** [CntoDev/compositions#190]
I was playing with different types of magazines and, generally, our ineffectiveness against infantry armor, and @JamesTheClarke mentioned something about maybe wanting to have 5.56x45mm close to how 5.45x39mm hits (for balance reasons?), so here I've compiled a list of some interesting 5.56mm magazine/ammo options we could switch to for TFN/US to make them more effective (if such thing is wanted).

Note that even with #141 and proper Headless Client transfer, it still takes 4-5 direct chest shots @ 100m to kill a typical MSV RHS Russian soldier. With our current ammo.

___

The values below are from a magazine config and its related ammo (bullet) config and together form a "damage" approximation.
* `mass` is how much space a magazine takes up in inventory
* `initSpeed` is the initial velocity a bullet leaves the muzzle (further modified by muzzle accessories, weapon barrel, etc.)
* `typicalSpeed` sets the scaling of the `hit` value (below), eg. the soldier takes `hit` damage from a bullet travelling at `typicalSpeed`
* `airFriction` is how fast a bullet loses its speed as it travels
* `caliber` is bullet penetration multiplier, `caliber * speed * material_penetrability / 1000` is how many millimeters it burrows (theoretically), AFAIK
* `hit` is a straight damage to (reduction of) the soldier hitpoints, more hit = more damage = more dead

___

Let's start with what we already have.

The TFN faction uses:
```
rhs_mag_30Rnd_556x45_M855A1_Stanag:
- mass: 9.35
- initSpeed: 960
- ammo: rhs_ammo_556x45_M855A1_Ball
  - typicalSpeed: 960
  - airFriction: -0.000772
  - caliber: 0.65
  - hit: 9

rhs_mag_30Rnd_556x45_M855A1_Stanag_Tracer_Red:
- mass: 9.35
- initSpeed: 960
- ammo: rhs_ammo_556x45_M855A1_Ball_Red
  - typicalSpeed: 960
  - airFriction: -0.000772
  - caliber: 0.65
  - hit: 9
```

US has the same thing in a different visual package:
```
rhs_mag_30Rnd_556x45_M855A1_PMAG:
- mass: 9.35
- initSpeed: 960
- ammo: rhs_ammo_556x45_M855A1_Ball
  - typicalSpeed: 960
  - airFriction: -0.000772
  - caliber: 0.65
  - hit: 9

rhs_mag_30Rnd_556x45_M855A1_PMAG_Tracer_Red:
- mass: 9.35
- initSpeed: 960
- ammo: rhs_ammo_556x45_M855A1_Ball_Red
  - typicalSpeed: 960
  - airFriction: -0.000772
  - caliber: 0.65
  - hit: 9
```

RU have lighter mags with bigger caliber and notably more damage, at a slight speed loss. Interestingly, while 5.56mm tracer ammo has no change to damage, 5.45mm AK tracer ammo seems close to useless.
```
rhs_30Rnd_545x39_7N22_plum_AK:
- mass: 9.09
- initSpeed: 890
- ammo: rhs_B_545x39_7N22_Ball
  - typicalSpeed: 890
  - airFriction: -0.00085
  - caliber: 0.939794
  - hit: 10.1

rhs_30Rnd_545x39_AK_plum_green:
- mass: 9.09
- initSpeed: 883
- ammo: rhs_B_545x39_Ball_Tracer_Green
  - typicalSpeed: 915
  - airFriction: -0.0016564
  - caliber: 0.216216
  - hit: 9
```
Needless to say, the non-tracer variant seems pretty OP considering that it's both a smaller and shorter caliber. My suspicion is that RHS just re-used the 7.62x39mm values.

Now let's look at some alternatives to the 5.56mm we use, starting with HLC (NIArms):
```
hlc_30rnd_556x45_SOST:
- mass: 12
- initSpeed: 954.4
- ammo: HLC_556NATO_SOST
  - typicalSpeed: 954.4
  - airFriction: -0.00130785
  - caliber: 0.684
  - hit: 10.7

hlc_30rnd_556x45_SPR:
- mass: 14
- initSpeed: 868.7
- ammo: HLC_556NATO_SPR
  - typicalSpeed: 868.7
  - airFriction: -0.00108679
  - caliber: 0.189
  - hit: 11.12

hlc_30rnd_556x45_EPR:
- mass: 11
- initSpeed: 974.8
- ammo: HLC_556NATO_EPR
  - typicalSpeed: 974.8
  - airFriction: -0.0012744
  - caliber: 0.964
  - hit: 10.28

hlc_30rnd_556x45_t:
- mass: 11
- initSpeed: 974.8
- ammo: HLC_556NATO_EPR_Tracer
  - typicalSpeed: 974.8
  - airFriction: -0.0012744
  - caliber: 0.964
  - hit: 10.28
```
The EPR rounds look good (actually better than 5.45x39mm), but the magazines are rather heavy and the high speed would actually decrease the `hit` damage transferred (due to how the simulation works).

Let's look at vanilla:
```
30Rnd_556x45_Stanag:
- mass: 8
- initSpeed: 909
- ammo: B_556x45_Ball
  - typicalSpeed: 920
  - airFriction: -0.00130094
  - caliber: 0.869565
  - hit: 9

30Rnd_556x45_Stanag_Tracer_Red:
- mass: 8
- initSpeed: 869
- ammo: B_556x45_Ball_Tracer_Red
  - typicalSpeed: 920
  - airFriction: -0.00130094
  - caliber: 0.869565
  - hit: 9
```
Not something to write home about, but a definite penetration improvement over what we have, not to mention lighter.

ACE3 has its own vanilla modifications:
```
ACE_30Rnd_556x45_Stanag_Mk262_mag:
- mass: 8
- initSpeed: 832
- ammo: ACE_556x45_Ball_Mk262
  - typicalSpeed: 920
  - airFriction: -0.00111805
  - caliber: 0.869565
  - hit: 9

ACE_30Rnd_556x45_Stanag_Mk318_mag:
- mass: 8
- initSpeed: 923
- ammo: ACE_556x45_Ball_Mk318
  - typicalSpeed: 920
  - airFriction: -0.0012588
  - caliber: 0.869565
  - hit: 9

ACE_30Rnd_556x45_Stanag_M995_AP_mag:
- mass: 8
- initSpeed: 875
- ammo: ACE_556x45_Ball_M995_AP
  - typicalSpeed: 920
  - airFriction: -0.00126182
  - caliber: 1.6
  - hit: 9
```
If we were to choose between vanilla and ACE, the ACE Mk318 is probably better due to the slightly higher speed. The high caliber of M995_AP would easily pierce most vests, and - in a round about way - could compensate for the difference to 5.45x39mm even with a lower `hit` value (which will be even below `9`, because it's `9` @ 920m/s, while `initSpeed` is 875 already).

Looking at magazine options in RHS, they aren't great - everything has too small caliber to be truly effective against RU vests.
```
rhs_mag_30Rnd_556x45_M193_Stanag:
- mass: 9.35
- initSpeed: 974
- ammo: rhs_ammo_556x45_M193_Ball
  - typicalSpeed: 974
  - airFriction: -0.00077
  - caliber: 0.533881
  - hit: 9.3

rhs_mag_30Rnd_556x45_M855_Stanag:
- mass: 9.35
- initSpeed: 948.842
- ammo: rhs_ammo_556x45_M855_Ball
  - typicalSpeed: 948.842
  - airFriction: -0.00076
  - caliber: 0.44
  - hit: 9

rhs_mag_30Rnd_556x45_M855A1_Stanag:
- mass: 9.35
- initSpeed: 960
- ammo: rhs_ammo_556x45_M855A1_Ball
  - typicalSpeed: 960
  - airFriction: -0.000772
  - caliber: 0.65
  - hit: 9

rhs_mag_30Rnd_556x45_Mk262_Stanag:
- mass: 9.35
- initSpeed: 838.2
- ammo: rhs_ammo_556x45_Mk262_Ball
  - typicalSpeed: 838.2
  - airFriction: -0.00066
  - caliber: 0.677
  - hit: 10.3

rhs_mag_30Rnd_556x45_Mk318_Stanag:
- mass: 9.35
- initSpeed: 950.366
- ammo: rhs_ammo_556x45_Mk318_Ball
  - typicalSpeed: 950
  - airFriction: -0.00076
  - caliber: 0.64
  - hit: 9.55
```
But if we were to choose, Mk318 or Mk262 are still in a different league from the rest of RHS 5.56mm mags.

___

Finally, we could create our own custom magazines/ammo, or mod any of these, but I'd consider that a last-ditch effort as it would only add to the maintenance burden and potentially open doors to more and more overhead (modding vests, uniforms, RPGs, magazine weight, like I used to do before).

The far easier solution is to just choose something better from the above, and do a string replace in a composition `.sqe`. If the chosen option is heavier, then double-checking for overloaded units should be done.

Anyway, I just provide the data, the decision is up to you.

If I was to make a recommendation, I'd go for
* `ACE_30Rnd_556x45_Stanag_Mk318_mag` + `30Rnd_556x45_Stanag_Tracer_Red`
* OR `hlc_30rnd_556x45_EPR` + `hlc_30rnd_556x45_t` and adjust mag amounts to prevent inventory overload

**Comment by freghar** [comment]
Honestly, `ACE_30Rnd_556x45_Stanag_M995_AP_mag` might seem OP on paper, but they aren't really that much better, so I'd propose:
 * `ACE_30Rnd_556x45_Stanag_M995_AP_mag` as a replacement for `rhs_mag_30Rnd_556x45_M855A1_Stanag`
    * the ACE mags have weight 8 instead of 9.35, so they'll also be lighter, meaning no overweight issues
 * `30Rnd_556x45_Stanag_Tracer_Red` as a replacement for `rhs_mag_30Rnd_556x45_M855A1_Stanag_Tracer_Red`
    * same with weight 8 vs 9.35, .. plus a little bit better than the `rhs_mag_`

**Comment by Shiny-CNTO** [comment]
I hard agree with a change to stronger bullets.

**Comment by Seb105** [comment]
What about the 5.45 ammo for our Russian faction?

**Comment by Seb105** [comment]
I'm happy to do this change as the best way to do it is a find and replace in the composition sqm

**Comment by freghar** [comment]
> What about the 5.45 ammo for our Russian faction?

Well, this is what we have:

```
rhs_30Rnd_545x39_7N22_plum_AK:
- mass: 9.09
- initSpeed: 890
- ammo: rhs_B_545x39_7N22_Ball
  - typicalSpeed: 890
  - airFriction: -0.00085
  - caliber: 0.939794
  - hit: 10.1

rhs_30Rnd_545x39_AK_plum_green:
- mass: 9.09
- initSpeed: 883
- ammo: rhs_B_545x39_Ball_Tracer_Green
  - typicalSpeed: 915
  - airFriction: -0.0016564
  - caliber: 0.216216
  - hit: 9
```

and this is what's available:
```
rhs_30Rnd_545x39_7N10_AK:
- mass: 9.09
- initSpeed: 880
- ammo: rhs_B_545x39_7N10_Ball
  - typicalSpeed: 880
  - airFriction: -0.001139
  - caliber: 0.618357
  - hit: 9.5

rhs_30Rnd_545x39_7N22_AK:
- mass: 9.09
- initSpeed: 890
- ammo: rhs_B_545x39_7N22_Ball
  - typicalSpeed: 890
  - airFriction: -0.00085
  - caliber: 0.939794
  - hit: 10.1

rhs_30Rnd_545x39_7N6_green_AK:
- mass: 9.09
- initSpeed: 915
- ammo: rhs_B_545x39_Ball
  - typicalSpeed: 915
  - airFriction: -0.0016564
  - caliber: 0.216216
  - hit: 9

rhs_30Rnd_545x39_7N6M_green_AK:
- mass: 9.09
- initSpeed: 880
- ammo: rhs_B_545x39_7N6_Ball
  - typicalSpeed: 880
  - airFriction: -0.001139
  - caliber: 0.231884
  - hit: 9.3

30Rnd_545x39_Mag_F:
- mass: 8
- initSpeed: 735
- ammo: B_545x39_Ball_F
  - typicalSpeed: 880
  - airFriction: -0.001195
  - caliber: 0.6
  - hit: 8

30Rnd_545x39_Mag_Tracer_F:
- mass: 8
- initSpeed: 735
- ammo: B_545x39_Ball_F
  - typicalSpeed: 880
  - airFriction: -0.001195
  - caliber: 0.6
  - hit: 8

hlc_30Rnd_545x39_B_AK:
- mass: 11.63
- initSpeed: 879.9
- ammo: FH_545x39_Ball
  - typicalSpeed: 879.9
  - airFriction: -0.0012003
  - caliber: 0.543
  - hit: 8.1

hlc_30Rnd_545x39_t_ak:
- mass: 11.33
- initSpeed: 879.9
- ammo: FH_545x39_Tracer
  - typicalSpeed: 879.9
  - airFriction: -0.0012003
  - caliber: 0.543
  - hit: 8.1
```

We could nerf the faction down to 7N10, which would bring it on the current level of US/TFN, though that's still ignoring armor differences. FTR, 7N10 is what the MSV AI faction uses.

**Comment by freghar** [comment]
To complete the picture, here are some vests and their armor values, reference https://community.bistudio.com/wiki/Arma_3:_Soldier_Protection for explanation about hitpoints and passtrough; otherwise `mass` is the weight of the empty vest itself, `maximumLoad` is how much it can carry.

I didn't bother copy/pasting vest names from TFN as there's just a few:
```
cnto_flecktarn_v_grassland:
- mass: 100
- maximumLoad: 140 (from Supply140)
  - armor: 20 ; passThrough: 0.2 ; hitpointName: HitChest
  - armor: 20 ; passThrough: 0.2 ; hitpointName: HitDiaphragm
  - armor: 20 ; passThrough: 0.2 ; hitpointName: HitAbdomen
  - armor: 0 ; passThrough: 0.2 ; hitpointName: HitBody

cnto_flecktarn_v_h_grassland:
- mass: 100
- maximumLoad: 140 (from Supply140)
  - armor: 8 ; passThrough: 0.5 ; hitpointName: HitNeck
  - armor: 8 ; passThrough: 0.5 ; hitpointName: HitArms
  - armor: 78 ; passThrough: 0.6 ; hitpointName: HitChest
  - armor: 78 ; passThrough: 0.6 ; hitpointName: HitDiaphragm
  - armor: 16 ; passThrough: 0.3 ; hitpointName: HitAbdomen
  - armor: 16 ; passThrough: 0.3 ; hitpointName: HitPelvis
  - armor: 0 ; passThrough: 0.6 ; hitpointName: HitBody

cnto_flecktarn_v_l_grassland:
- mass: 80
- maximumLoad: 140 (from Supply140)
  - armor: 16 ; passThrough: 0.3 ; hitpointName: HitChest
  - armor: 16 ; passThrough: 0.3 ; hitpointName: HitDiaphragm
  - armor: 16 ; passThrough: 0.3 ; hitpointName: HitAbdomen
  - armor: 0 ; passThrough: 0.3 ; hitpointName: HitBody

cnto_flecktarn_v_s_grassland:
- mass: 120
- maximumLoad: 100 (from Supply100)
  - armor: 8 ; passThrough: 0.5 ; hitpointName: HitNeck
  - armor: 8 ; passThrough: 0.5 ; hitpointName: HitArms
  - armor: 24 ; passThrough: 0.1 ; hitpointName: HitChest
  - armor: 24 ; passThrough: 0.1 ; hitpointName: HitDiaphragm
  - armor: 24 ; passThrough: 0.1 ; hitpointName: HitAbdomen
  - armor: 0 ; passThrough: 0.1 ; hitpointName: HitBody
```

For the US, I copy/pasted classnames of SL, Medic, then FTL, AR, AAR and AT:
```
rhsusf_spcs_ocp_squadleader:
- mass: 100
- maximumLoad: 140 (from Supply140)
  - armor: 28 ; passThrough: 0.1 ; hitpointName: HitChest
  - armor: 28 ; passThrough: 0.1 ; hitpointName: HitDiaphragm
  - armor: 12 ; passThrough: 0.4 ; hitpointName: HitAbdomen
  - armor: 0 ; passThrough: 0.4 ; hitpointName: HitBody

rhsusf_spcs_ocp_medic:
- mass: 100
- maximumLoad: 140 (from Supply140)
  - armor: 28 ; passThrough: 0.1 ; hitpointName: HitChest
  - armor: 28 ; passThrough: 0.1 ; hitpointName: HitDiaphragm
  - armor: 12 ; passThrough: 0.4 ; hitpointName: HitAbdomen
  - armor: 0 ; passThrough: 0.4 ; hitpointName: HitBody

rhsusf_spcs_ocp_grenadier:
- mass: 100
- maximumLoad: 140 (from Supply140)
  - armor: 28 ; passThrough: 0.1 ; hitpointName: HitChest
  - armor: 28 ; passThrough: 0.1 ; hitpointName: HitDiaphragm
  - armor: 12 ; passThrough: 0.4 ; hitpointName: HitAbdomen
  - armor: 0 ; passThrough: 0.4 ; hitpointName: HitBody

rhsusf_spcs_ocp_saw:
- mass: 100
- maximumLoad: 140 (from Supply140)
  - armor: 28 ; passThrough: 0.1 ; hitpointName: HitChest
  - armor: 28 ; passThrough: 0.1 ; hitpointName: HitDiaphragm
  - armor: 12 ; passThrough: 0.4 ; hitpointName: HitAbdomen
  - armor: 0 ; passThrough: 0.4 ; hitpointName: HitBody

rhsusf_spcs_ocp_teamleader:
- mass: 100
- maximumLoad: 140 (from Supply140)
  - armor: 28 ; passThrough: 0.1 ; hitpointName: HitChest
  - armor: 28 ; passThrough: 0.1 ; hitpointName: HitDiaphragm
  - armor: 12 ; passThrough: 0.4 ; hitpointName: HitAbdomen
  - armor: 0 ; passThrough: 0.4 ; hitpointName: HitBody

rhsusf_spcs_ocp_rifleman_alt:
- mass: 100
- maximumLoad: 140 (from Supply140)
  - armor: 28 ; passThrough: 0.1 ; hitpointName: HitChest
  - armor: 28 ; passThrough: 0.1 ; hitpointName: HitDiaphragm
  - armor: 12 ; passThrough: 0.4 ; hitpointName: HitAbdomen
  - armor: 0 ; passThrough: 0.4 ; hitpointName: HitBody
```

Same for RU:
```
rhs_6b23_digi_6sh92_Vog_Radio_Spetsnaz:
- mass: 75
- maximumLoad: 120 (from Supply120)
  - armor: 12 ; passThrough: 0.3 ; hitpointName: HitNeck
  - armor: 22 ; passThrough: 0.3 ; hitpointName: HitChest
  - armor: 25 ; passThrough: 0.3 ; hitpointName: HitDiaphragm
  - armor: 25 ; passThrough: 0.3 ; hitpointName: HitAbdomen
  - armor: 0 ; passThrough: 0.3 ; hitpointName: HitBody

rhs_6b23_medic:
- mass: 80
- maximumLoad: 130 (from Supply130)
  - armor: 8 ; passThrough: 0.4 ; hitpointName: HitNeck
  - armor: 22 ; passThrough: 0.3 ; hitpointName: HitChest
  - armor: 22 ; passThrough: 0.3 ; hitpointName: HitDiaphragm
  - armor: 22 ; passThrough: 0.3 ; hitpointName: HitAbdomen
  - armor: 0 ; passThrough: 0.3 ; hitpointName: HitBody

rhs_6b23_6sh92_vog_headset:
- mass: 80
- maximumLoad: 120 (from Supply120)
  - armor: 12 ; passThrough: 0.3 ; hitpointName: HitNeck
  - armor: 22 ; passThrough: 0.3 ; hitpointName: HitChest
  - armor: 25 ; passThrough: 0.3 ; hitpointName: HitDiaphragm
  - armor: 25 ; passThrough: 0.3 ; hitpointName: HitAbdomen
  - armor: 0 ; passThrough: 0.3 ; hitpointName: HitBody

rhs_6b23_digi_vydra_3m:
- mass: 75
- maximumLoad: 100 (from Supply100)
  - armor: 8 ; passThrough: 0.4 ; hitpointName: HitNeck
  - armor: 22 ; passThrough: 0.3 ; hitpointName: HitChest
  - armor: 25 ; passThrough: 0.3 ; hitpointName: HitDiaphragm
  - armor: 25 ; passThrough: 0.3 ; hitpointName: HitAbdomen
  - armor: 0 ; passThrough: 0.3 ; hitpointName: HitBody

rhs_6b23_digi_6sh92_headset:
- mass: 75
- maximumLoad: 100 (from Supply100)
  - armor: 12 ; passThrough: 0.3 ; hitpointName: HitNeck
  - armor: 22 ; passThrough: 0.3 ; hitpointName: HitChest
  - armor: 25 ; passThrough: 0.3 ; hitpointName: HitDiaphragm
  - armor: 25 ; passThrough: 0.3 ; hitpointName: HitAbdomen
  - armor: 0 ; passThrough: 0.3 ; hitpointName: HitBody

rhs_6b23_6sh116_od:
- mass: 80
- maximumLoad: 140 (from Supply140)
  - armor: 12 ; passThrough: 0.3 ; hitpointName: HitNeck
  - armor: 22 ; passThrough: 0.3 ; hitpointName: HitChest
  - armor: 25 ; passThrough: 0.3 ; hitpointName: HitDiaphragm
  - armor: 25 ; passThrough: 0.3 ; hitpointName: HitAbdomen
  - armor: 0 ; passThrough: 0.3 ; hitpointName: HitBody
```

...  
The RU MSV AI faction uses 6b23 vests, so their armor values are going to be similar to these values.

So the conclusion is that the RU vests not only double the abdomen protection, but they also cover a bigger surface area (neck), making them more likely to shield from a critical hit.

I also tried comparing helmets between our US and RU factions, but they're exactly the same.
